name: Mirror to GitLab
on:
  push:
    branches: ["**"] # all branches
    tags: ["*"] # all tags
  delete: # branch/tag deletions (no filters allowed)

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror default branch safely
        env:
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          DEF: ${{ github.event.repository.default_branch || 'master' }}
        run: |
          set -euo pipefail
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@${GITLAB_URL#https://}"
          git fetch origin --prune --tags
          git fetch gitlab --prune || true

          SRC="refs/remotes/origin/${DEF}"
          DST="refs/heads/${DEF}"

          if git rev-parse "refs/remotes/gitlab/${DEF}" >/dev/null 2>&1 \
            && ! git merge-base --is-ancestor "refs/remotes/gitlab/${DEF}" "$SRC"; then
            echo "::warning::${DEF} diverged or blocked; pushing to mirror/${DEF}."
            git push gitlab "${SRC}:refs/heads/mirror/${DEF}"
            # tags (no force)
            git push --prune gitlab refs/tags/*:refs/tags/* || true
          else
            git push --prune gitlab "${SRC}:${DST}"
            git push --prune gitlab refs/tags/*:refs/tags/* || true
          fi
