name: Mirror to GitLab
on:
  push:
    branches: ["**"] # all branches
    tags: ["*"] # all tags
  delete: # branch/tag deletions (no filters allowed)

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror GitHub -> GitLab (force only default branch)
        env:
          GITLAB_URL: ${{ secrets.GITLAB_URL }} # https://gitlab.com/<group>/<repo>.git
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }} # PAT with write_repository
          DEF: ${{ github.event.repository.default_branch || 'master' }}
        run: |
          set -euo pipefail

          # Add remote with token
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@${GITLAB_URL#https://}"

          # Make sure we have latest from GitHub
          git fetch origin --prune --tags

          # 1) Force update the default branch on GitLab to match GitHub
          #    Requires: Allowed to push = Developers (or you), and Allow force push = enabled for DEF
          git push gitlab +refs/remotes/origin/${DEF}:refs/heads/${DEF}

          # 2) Push all other branches (fast-forward only), skipping HEAD and the default (already handled)
          git for-each-ref --format='%(refname:strip=3)' refs/remotes/origin | grep -v '^HEAD$' | grep -v "^${DEF}$" | while read BR; do
            echo "Pushing branch ${BR}"
            git push gitlab "refs/remotes/origin/${BR}:refs/heads/${BR}" || \
              echo "::warning::Fast-forward failed for ${BR}; skipping."
          done

          # 3) Push all tags (no force)
          git push --prune gitlab refs/tags/*:refs/tags/* || true
