name: Mirror to GitLab
on:
  push:
    branches: ["**"] # all branches
    tags: ["*"] # all tags
  delete: # branch/tag deletions (no filters allowed)

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push branches & tags from GitHub → GitLab (fast-forward only)
        env:
          GITLAB_URL: ${{ secrets.GITLAB_URL }} # HTTPS form
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # Add GitLab remote using HTTPS + token
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@${GITLAB_URL#https://}"

          # Make sure we have all refs from GitHub (origin)
          git fetch origin --prune --tags

          # Push branches: take origin/* as the source, so we avoid detached HEAD issues
          git push --prune gitlab refs/remotes/origin/*:refs/heads/*

          # Push tags (no force)
          git push --prune gitlab refs/tags/*:refs/tags/*
